In [122]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,maddur,100.0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,blr,200.0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,k.m doodi,50000.0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,mandya,50000.0
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,mysore,20000.0

In [123]:
df.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,NaN,NaN
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,NaN,NaN
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,NaN,NaN
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,NaN,NaN
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,NaN,NaN

In [124]:
df.shape

(395, 35)

In [125]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3', 'City', 'Salary'],
      dtype='str')

In [126]:
df.dtypes

school            str
sex               str
age             int64
address           str
famsize           str
Pstatus           str
Medu            int64
Fedu            int64
Mjob              str
Fjob              str
reason            str
guardian          str
traveltime      int64
studytime       int64
failures        int64
schoolsup         str
famsup            str
paid              str
activities        str
nursery           str
higher            str
internet          str
romantic          str
famrel          int64
freetime        int64
goout           int64
Dalc            int64
Walc            int64
health          int64
absences        int64
G1              int64
G2              int64
G3              int64
City              str
Salary        float64
dtype: object

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 35 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    str
 1   sex         395 non-null    str
 2   age         395 non-null    int64
 3   address     395 non-null    str
 4   famsize     395 non-null    str
 5   Pstatus     395 non-null    str
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    str
 9   Fjob        395 non-null    str
 10  reason      395 non-null    str
 11  guardian    395 non-null    str
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    str
 16  famsup      395 non-null    str
 17  paid        395 non-null    str
 18  activities  395 non-null    str
 19  nursery     395 non-null    str
 20  higher      395 non-null    str
 21  internet    395 non-null    str
 22  romantic    395 non-null    str
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
 33  City        353 non-null    str
 34  Salary      16 non-null     float64
dtypes: float64(1), int64(16), str(18)
memory usage: 80.3 KB

In [128]:
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,Salary
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,16.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190,41196.687500
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443,34191.215774
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000,100.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000,16391.500000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000,45128.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000,50631.250000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000,120000.000000

In [129]:
df["age"].mean()

np.float64(16.696202531645568)

In [130]:
df["age"].median()

np.float64(17.0)

In [131]:
df["age"].mode()

0    16
Name: age, dtype: int64

In [132]:
df["age"].var()

np.float64(1.6282850350189553)

In [133]:
df["age"].std()

np.float64(1.2760427246056283)

In [134]:
df["age"].min()

np.int64(15)

In [135]:
df["age"].max()

np.int64(22)

In [136]:
df["age"].count()

np.int64(395)

In [137]:
df["City"].unique()

<StringArray>
['maddur', 'blr', 'k.m doodi', 'mandya', 'mysore', 'ramnagar', 'cpt', nan]
Length: 8, dtype: str

In [138]:
df["City"].nunique()

7

In [139]:
df["City"].value_counts()

City
blr          88
maddur       45
k.m doodi    44
mandya       44
mysore       44
ramnagar     44
cpt          44
Name: count, dtype: int64

In [140]:
df.isnull()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
391,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
392,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
393,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
394,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [141]:
df.isnull().sum()

school          0
sex             0
age             0
address         0
famsize         0
Pstatus         0
Medu            0
Fedu            0
Mjob            0
Fjob            0
reason          0
guardian        0
traveltime      0
studytime       0
failures        0
schoolsup       0
famsup          0
paid            0
activities      0
nursery         0
higher          0
internet        0
romantic        0
famrel          0
freetime        0
goout           0
Dalc            0
Walc            0
health          0
absences        0
G1              0
G2              0
G3              0
City           42
Salary        379
dtype: int64

In [142]:
df.isnull().mean()*100

school         0.000000
sex            0.000000
age            0.000000
address        0.000000
famsize        0.000000
Pstatus        0.000000
Medu           0.000000
Fedu           0.000000
Mjob           0.000000
Fjob           0.000000
reason         0.000000
guardian       0.000000
traveltime     0.000000
studytime      0.000000
failures       0.000000
schoolsup      0.000000
famsup         0.000000
paid           0.000000
activities     0.000000
nursery        0.000000
higher         0.000000
internet       0.000000
romantic       0.000000
famrel         0.000000
freetime       0.000000
goout          0.000000
Dalc           0.000000
Walc           0.000000
health         0.000000
absences       0.000000
G1             0.000000
G2             0.000000
G3             0.000000
City          10.632911
Salary        95.949367
dtype: float64

In [143]:
df.dropna()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,maddur,100.0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,blr,200.0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,k.m doodi,50000.0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,mandya,50000.0
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,mysore,20000.0
5,GP,M,16,U,LE3,T,4,3,services,other,...,2,1,2,5,10,15,15,15,blr,30000.0
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,1,1,3,0,12,12,11,ramnagar,1500.0
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,1,1,6,6,5,6,cpt,120000.0
8,GP,M,15,U,LE3,A,3,2,services,other,...,2,1,1,1,0,16,18,19,maddur,45000.0
9,GP,M,15,U,GT3,T,3,4,other,other,...,1,1,1,5,0,14,15,15,blr,78000.0
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,1,2,2,0,10,8,9,k.m doodi,90000.0
11,GP,F,15,U,GT3,T,2,1,services,other,...,2,1,1,4,4,10,12,12,mandya,50000.0
12,GP,M,15,U,LE3,T,4,4,health,services,...,3,1,3,5,2,14,14,14,mysore,21000.0
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,3,1,2,3,2,10,10,11,blr,52525.0
14,GP,M,15,U,GT3,A,2,2,other,other,...,2,1,1,3,0,14,16,16,ramnagar,45256.0
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,1,2,2,4,14,14,14,cpt,5566.0

In [144]:
df.fillna(0)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,maddur,100.0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,blr,200.0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,k.m doodi,50000.0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,mandya,50000.0
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,mysore,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,0,0.0
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,0,0.0
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,0,0.0
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,0,0.0
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,0,0.0

In [145]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
390    False
391    False
392    False
393    False
394    False
Length: 395, dtype: bool

In [146]:
df.duplicated().sum()

np.int64(0)

In [147]:
df.drop_duplicates()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,maddur,100.0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,blr,200.0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,k.m doodi,50000.0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,mandya,50000.0
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,mysore,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,NaN,NaN
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,NaN,NaN
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,NaN,NaN
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,NaN,NaN
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,NaN,NaN

In [148]:
df["age"]

0      18
1      17
2      15
3      15
4      16
       ..
390    20
391    17
392    21
393    18
394    19
Name: age, Length: 395, dtype: int64

In [149]:
df[["age","Salary"]]

     age   Salary
0     18    100.0
1     17    200.0
2     15  50000.0
3     15  50000.0
4     16  20000.0
..   ...      ...
390   20      NaN
391   17      NaN
392   21      NaN
393   18      NaN
394   19      NaN

[395 rows x 2 columns]

In [150]:
df.iloc[0:5]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,maddur,100.0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,blr,200.0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,k.m doodi,50000.0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,mandya,50000.0
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,mysore,20000.0

In [151]:
df[df["age"] > 20]

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
247,GP,M,22,U,GT3,T,3,1,services,services,...,5,5,5,1,16,6,8,8,cpt,NaN
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,NaN,NaN

In [152]:
df.sort_values("age")

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
130,GP,F,15,R,GT3,T,3,4,services,teacher,...,2,2,2,5,0,12,0,0,k.m doodi,NaN
102,GP,M,15,U,GT3,T,4,4,services,other,...,3,1,1,5,4,10,13,14,ramnagar,NaN
103,GP,F,15,U,GT3,T,3,2,services,other,...,5,1,1,2,26,7,6,6,cpt,NaN
104,GP,M,15,U,GT3,A,3,4,services,other,...,4,1,1,1,0,16,18,18,maddur,NaN
105,GP,F,15,U,GT3,A,3,3,other,health,...,3,1,1,4,10,10,11,11,blr,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
376,MS,F,20,U,GT3,T,4,2,health,other,...,3,1,1,3,4,15,14,15,NaN,NaN
306,GP,M,20,U,GT3,A,3,2,services,other,...,3,1,1,5,0,17,18,18,k.m doodi,NaN
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,NaN,NaN
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,NaN,NaN
247,GP,M,22,U,GT3,T,3,1,services,services,...,5,5,5,1,16,6,8,8,cpt,NaN

In [153]:
df.rename(columns={"age":"age_Years"})

,school,sex,age_Years,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,maddur,100.0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,blr,200.0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,k.m doodi,50000.0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,mandya,50000.0
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,mysore,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,NaN,NaN
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,NaN,NaN
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,NaN,NaN
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,NaN,NaN
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,NaN,NaN

In [154]:
df["Bonus"] = df["Salary"]*0.5

In [155]:
df.drop("Bonus", axis=1)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,goout,Dalc,Walc,health,absences,G1,G2,G3,City,Salary
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,1,1,3,6,5,6,6,maddur,100.0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,1,1,3,4,5,5,6,blr,200.0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,2,2,3,3,10,7,8,10,k.m doodi,50000.0
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,1,1,5,2,15,14,15,mandya,50000.0
4,GP,F,16,U,GT3,T,3,3,other,other,...,2,1,2,5,4,6,10,10,mysore,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,MS,M,20,U,LE3,A,2,2,services,services,...,4,4,5,4,11,9,9,9,NaN,NaN
391,MS,M,17,U,LE3,T,3,1,services,services,...,5,3,4,2,3,14,16,16,NaN,NaN
392,MS,M,21,R,GT3,T,1,1,other,other,...,3,3,3,3,3,10,8,7,NaN,NaN
393,MS,M,18,R,LE3,T,3,2,services,other,...,1,3,4,5,0,11,12,10,NaN,NaN
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,3,3,5,5,8,9,9,NaN,NaN

In [156]:
df.groupby("absences")

In [157]:
df.groupby("absences")["Salary"].mean()

absences
0     51951.2
1         NaN
2     41175.0
3         NaN
4     18941.5
5         NaN
6     60050.0
7         NaN
8         NaN
9         NaN
10    40000.0
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN
26        NaN
28        NaN
30        NaN
38        NaN
40        NaN
54        NaN
56        NaN
75        NaN
Name: Salary, dtype: float64